<p >
  <a href="https://cypresscove.foxycart.com/cart?cart=view" class="miniCart">
    <span class="itemCount"><span data-fc-id="minicart-quantity">0</span></span> 
    <span class="cartPrice">Total: $<span data-fc-id="minicart-order-total">0</span></span>
    <span class="cartText">View Cart / Checkout</span>
  </a>
</p>

<?php if ($page->id != "1092"): ?>
<p class="backToStoreHome"><a href="/store/">&lt;&lt; More products</a></p>
<?php endif ?>